### Review and "mise à jour" before moving on to micro-bio module

1. Do some basics 
2. Develop some advanced applications

#### References
1. Python for data analysis
2. Think stats: exploratory data analysis
3. https://pandas.pydata,org

#### Purpose
1. Work in the abstract (its good for the brain)
2. Keep up to date with changes in the library
3. Explore new ways of doing common tasks --- get better

In [1]:
import numpy as np

In [2]:
# create an array
data = np.random.randn(2, 3)
data

array([[-0.08614796,  0.07303568, -0.65132975],
       [-0.32243074,  1.50405378, -0.23479463]])

In [3]:
# each element * 10
data*10

array([[ -0.86147962,   0.73035684,  -6.51329754],
       [ -3.22430738,  15.0405378 ,  -2.34794627]])

In [5]:
# each element is added together
data + data

array([[-0.17229592,  0.14607137, -1.30265951],
       [-0.64486148,  3.00810756, -0.46958925]])

In [9]:
a = data.shape
b = data.dtype
print(a, b)

(2, 3) float64


In [12]:
d_1 = [1, 3, 4, 6, 8, 9]
a_1 = np.array(d_1)
a_1, d_1

(array([1, 3, 4, 6, 8, 9]), [1, 3, 4, 6, 8, 9])

In [13]:
# multidimensional arrays
d_2 = [[3, 4, 5, 6, 7], [8, 9, 10, 11, 12]]
a_2 = np.array(d_2)
a_2.ndim, a_1.ndim

(2, 1)

In [14]:
a_2.shape, a_1.shape

((2, 5), (6,))

In [19]:
b = np.arange(15)
c = np.arange(15)
d_3 = np.array([b,c])
d_3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [20]:
d_3.shape, d_3.ndim

((2, 15), 2)

In [22]:
# and so on enough generating arrays
# declairing data types on nd.array
d_3 = np.array([b,c], dtype=np.float64)
d_3.dtype
#which is the default value for numpy arrays any way

dtype('float64')

In [23]:
# basic math operations
d_4 = np.array(b)
d_5 = np.array(c)
d = d_4*d_5
e = d_4-d_5
print(d, e)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [25]:
# each postion in array d_4 is mltiplied or subtracted to/from the cooresponding postion in d_5
# use a scalar, it propogates to across the array
d = d_4 +1
print(d, d_5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [26]:
# comparing the arrays gives a boolean array (must be the same size)
d > d_5
# remember we added 1 to d_4 to get d in the previous block

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [27]:
#slicing and indexing
# like python, but not really
d_5[5]

5

In [28]:
d_5[2:8]

array([2, 3, 4, 5, 6, 7])

In [29]:
d_5[0]

0

In [31]:
#setting values 
d_5[2:8] = 1
d_5
# the values is cast to all elements in the slice

array([ 0,  1,  1,  1,  1,  1,  1,  1,  8,  9, 10, 11, 12, 13, 14])

In [35]:
# in np the slice is a view on the original array
# not a copy so the following results
a_slice = d_5[9:14]
a_slice, d_5

(array([ 9, 10, 11, 12, 13]),
 array([ 0,  1,  1,  1,  1,  1,  1,  1,  8,  9, 10, 11, 12, 13, 14]))

In [36]:
# so change a value in a_slice and see what happens
a_slice[0] = 19
a_slice, d_5

(array([19, 10, 11, 12, 13]),
 array([ 0,  1,  1,  1,  1,  1,  1,  1,  8, 19, 10, 11, 12, 13, 14]))

In [ ]:
# see how the value is changed in the original array
#